[game]
hostname = "[RU]Ванилла Space Axolotl [LRP][MRP]"
desc = "Этот сервер - попытка показать русскому сообществу игры, что есть другая сторона, без душных правил и администраторов, где можно веселиться и наслаждаться игрой. Это достигнуто с помощью лишь перевода оффициальной сборки игры, у которой приятный баланс и простые правила."
maxplayers = 150
soft_max_players = 50
map_rotation = true
role_timers = false

[infolinks]
bug_report = "https://github.com/space-wizards/space-station-14/issues/new/choose"
discord    = "https://discord.gg/KtHkxwrFnU"
github     = "https://github.com/lzk228/space-axolotl-14"
appeal     = "https://discord.gg/KtHkxwrFnU"

[server]
rules_file = "AxolotlRuleset"

[rules]
time = 60.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e"

[vote]
restart_required_ratio = 0.7

[admin]
see_own_notes = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2

[atmos]
max_explosion_range = 5

[shuttle]
emergency_early_launch_allowed = true

[ic]
flavor_text = true
